### ISSUE TITLE
Multiple browser support

### ISSUE THREAD

**Issue by iainbeeston** [benpickles/aesthetic#2]
Would it be possible (using selenium) to specify different browsers as well as breakpoints?

**Comment by iainbeeston** [comment]
That was supposed to be a suggestion, not a question

**Comment by benpickles** [comment]
This is indeed one of the goals: eventually depend on Capybara and rely on you to bring your own driver(s). At the moment Poltergeist has the behaviour I want and sticking with a single driver removes a bunch of work that I don't want to have to tackle yet.
